### ISSUE TITLE
Pitch filter

### ISSUE THREAD

**Issue by jiayuzhang** [bartolsthoorn/NVDSP#19]
I'm very newbie to DSP, i'm looking for a novocaine filter similar to NewTimePitch Audio Unit. Any ideas?

**Comment by bartolsthoorn** [comment]
Hi, in that case I would recommend to just use the NewTimePitch unit. NVDSP filters work on raw audio data, which means that it is compatible with any other framework. You can combine NVDSP with the existing Audio Units. The same is true for Novocaine, you should be able to extend it with native audio stuff.
