### ISSUE TITLE
Can I detect gender of speaker?

### ISSUE THREAD

**Issue by cloudjanak** [bartolsthoorn/NVDSP#20]
Like by getting pitch of voice?

**Comment by bartolsthoorn** [comment]
I would recommend reading what the academic field of computer science has to offer. However, a heuristic approach I would try is the following:

Set up many narrow band-pass filters, forming a histogram with each bin representing a narrow range of frequencies. Measure the intensity/decibels for each bin. Compare this histogram to a histogram you collected of a female and male voice and see which one is the most similar. For this similarity check you can use a simple algorithm such as histogram correlation: http://docs.opencv.org/doc/tutorials/imgproc/histograms/histogram_comparison/histogram_comparison.html 

Also, in the future, please put more effort in making your Github issues less spammy.
