### ISSUE TITLE
How to make custom audio EQ

### ISSUE THREAD

**Issue by anil03** [bartolsthoorn/NVDSP#23]
Hello I want to make custom EQ for song which are playing.
i have apply
POP
JAZZ
ROCK
CLASSICAL
DEEP
DANCE
like etc
is that posible using.
please let me know

**Comment by bartolsthoorn** [comment]
The custom EQing settings you listed are just that: EQ settings. So for example, people used a 10-band Peaking EQ filter set-up and just preselected a few settings that they thought fitting for pop or jazz or rock etc. I don't have a list of those settings, but I imagine you will be able to find them somewhere online, or come up with your own.
Or is your question about detecting the genre (pop, jazz, rock..) automatically?
