### ISSUE TITLE
3-band EQ

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [bartolsthoorn/NVDSP#28]
OK -- I've looked through the 10-band EQ and it makes sense, but how would I go about using the high and low shelving filters?

In the high shelving filter, for example, is the `centerFrequency` the frequency above which the effect will be applied? Or is the `centerFrequency` the center, and `Q` controls the width of the shelf?

Thanks.

**Comment by bartolsthoorn** [comment]
For the shelving filter, it is the "shelf midpoint frequency" you are setting. For more practical information, you can look into the popular biquad filter cookbook: [Audio-EQ-Cookbook.txt](http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt).
