### ISSUE TITLE
Support with AVPlayer and AVAudioPlayer

### ISSUE THREAD

**Issue by kiritazilen** [bartolsthoorn/NVDSP#29]
Hello,

I want to equalizer with default AVPlayer and AVAudioPlayer for mac. So I can use It with default players or not.

Thanks

**Comment by bartolsthoorn** [comment]
NVDSP works simply on arrays of audio samples (raw audio data), so it should be possible to use it with any player if you are able to work on the raw audio samples (an array with audio samples, float values between -1.0 - 1.0) and pass these on to NVDSP.
