### ISSUE TITLE
How to filter audio that is hosted on server

### ISSUE THREAD

**Issue by devlonworks** [bartolsthoorn/NVDSP#32]
In my application , All audio is hosted on Online URL . Can you help me filter that audio by NVDSP?

Thank you

**Comment by bartolsthoorn** [comment]
NVDSP is a very minimal/simple library that just works on raw audio data. Raw audio data is just an array of floats, where the floats have values between -1.0 and 1.0, which are the audio samples.

If you are playing from a stream, you can just process each buffer separately right before you send it to the speakers for playback.

**Comment by devlonworks** [comment]
Can you provide some sample code for this for apply filter on stream ?

**Comment by bartolsthoorn** [comment]
I don't have sample code for specifically that, but in a way Novocaine has a similar scenario. You continuously record audio with the microphone, and send it out in buffers with the `setOutputBlock`. If you manage to play the stream with Novocaine (this is unrelated to NVDSP) you will be able to apply NVDSP easily! Have you tried following this path?
