### ISSUE TITLE
No tag 0.0.1

### ISSUE THREAD

**Issue by catskytw** [bartolsthoorn/NVDSP#35]
Hello there is no tag as 0.0.1 
which makes cocoapods error since in ur podspec:
s.source         = { :git => 'https://github.com/bartolsthoorn/NVDSP.git', :tag => 'v0.0.1' }

thx

**Comment by bartolsthoorn** [comment]
@catskytw sorry for the slow reply, I added a tag: [0.0.1](https://github.com/bartolsthoorn/NVDSP/releases/tag/0.0.1). I removed the tags before because I like to think of master as the latest stable build, instead of the tags.
