### ISSUE TITLE
Fail compile

### ISSUE THREAD

**Issue by doriansgithub** [bartolsthoorn/NVDSP#36]
If I use the latest from Novocaine, the project fails.  Works fine with the included Novocain folder.

**Comment by bartolsthoorn** [comment]
What specifically fails? NVDSP is actually built completely stand-alone form Novocaine. It uses only the fact that Novocaine works with raw audio data arrays (just arrays of floats) and processes directly on those arrays.

Did you try running the latest Novocaine version before adding the NVDSP files?
