### ISSUE TITLE
No tag v0.0.1

### ISSUE THREAD

**Issue by d370urn3ur** [bartolsthoorn/NVDSP#37]
As already noted in #35, there is no tag **v0.0.1**.  You created a tag **0.0.1** (without a 'v') but in the .podspec it's referenced as **v0.0.1** (with a 'v'), so you need to either add the **v** to the tag name or remove it from the podspec in order for the pod to work normally.  Otherwise users have to add NVDSP to their podfile  like this :

```
pod 'NVDSP', git: 'https://github.com/bartolsthoorn/NVDSP.git', branch: '0.0.1'
```

**Comment by bartolsthoorn** [comment]
Thanks a lot for pointing this out, I changed the tag to `v0.0.1`.
