### ISSUE TITLE
Feed it the next song...

### ISSUE THREAD

**Issue by doriansgithub** [bartolsthoorn/NVDSP#39]
I also can't figure out how to feed it another song.  It plays one song, then stops.

- (void)updateWithMediaItemURL:(NSURL *) itemURL  {

    _fileReader = [[AudioFileReader alloc]
                   initWithAudioFileURL:itemURL
                   samplingRate:audioManager.samplingRate
                   numChannels:audioManager.numOutputChannels];

        __block float lastTimeLeft = - 1.0f;
        float timeLeft = self.fileReader.duration - [self.fileReader getCurrentTime];

        if ( timeLeft > 1.1) { //&& timeLeft != lastTimeLeft
            lastTimeLeft = timeLeft;
        } else {
            [self pause];
            
            if (!self.fileReader.playing) {
                audioManager.outputBlock = nil;
                [self.mediaDelegate nextSongPlay];
            }
        }
        NSLog(@"%f", timeLeft);

        [audioManager setOutputBlock:^(float *data, UInt32 numFrames, UInt32 numChannels)   {
        [self.fileReader retrieveFreshAudio:data numFrames:numFrames numChannels:numChannels];

        PEQ.G = PEQ_centerFrequency;
        [PEQ filterData:data numFrames:numFrames numChannels:numChannels];
        [CDT counterClipping:data numFrames:numFrames numChannels:numChannels];
    }];
}

**Comment by K-Be** [comment]
Why you can't allocate other file reader for other song?

**Comment by doriansgithub** [comment]
I'm not sure.  That same delegate "[self mediaDelegate nextSongPlay];, works with other players.

The song length reaches 0, but somehow the player won't play the next song in the array.

**Comment by K-Be** [comment]
What are "players"? Novocaine does not contain such class. Novocaine is a library, that works with data buffers, that should contain datas of a sound. You should implement a player by your self. If you want, you can use AudioFileReader (to read data from a file), if you don't want you can write your custom data source to get data for Novocaine (for example, from memory of from a midi generator).       
If you want to play next sound, you should replace data reader with new data reader and put a new  data into Novocaine's inputBlock.

**Comment by doriansgithub** [comment]
Our main player (singleton), is able to use different players like the AVAudioPlayer, or StreamingKit player as needed.  

We use the file reader.  The short code sample shows the file reader being called.

Ok, we will look into having the two readers. 

Thanks.

**Comment by doriansgithub** [comment]
Hi, do we know if this player can play “gapless”?

Thanks,

Dorian

**Comment by K-Be** [comment]
If you give data “gapless”,  Novocaine will play it  “gapless”. Novocaine is not a player it does not have meaning of a song or play list. Novocaine just works with buffers of data. If you open AudioFileReader you will see that this class just reads data into supported format and sends it to the delegate.

**Comment by doriansgithub** [comment]
Ok, thank you.

**Comment by bartolsthoorn** [comment]
I will close this as it seems like you found the answer! 😄
