### ISSUE TITLE
How to get audio data to use from microphone.

### ISSUE THREAD

**Issue by jogasinghbajwa** [bartolsthoorn/NVDSP#40]
Hi, I'm working on iOS application which is written in Swift 5. 
I'm looking to create A weight bandpass filter.
My query is that currently, I am receiving audio samples through a microphone using tap.
How can I use a High bandpass filter on an audio stream coming from the microphone to evaluate dB value?

**Comment by bartolsthoorn** [comment]
Hi, Novocaine has an example of how to receive audio samples from the microphone.

Applying a bandpass filter (example in the README) and measure the level like this: https://github.com/bartolsthoorn/NVDSP#measure-db-level-ranging-from--510f-to-00f
